[package]
name = "axonyx-ui"
namespace = "@axonyx/ui"

[exports]
ax_root = "src"
css_root = "src/css"
css_entry = "src/css/index.css"
js_root = "src/js"
js_entry = "src/js/index.js"

[themes]
default = "silver"
available = ["bronze", "silver", "gold"]
