use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let target = out_dir.join("assets.rs");

    let css = collect_assets(&manifest_dir, "src/css").expect("css assets should collect");
    let js = collect_assets(&manifest_dir, "src/js").expect("js assets should collect");
    let foundry = collect_assets(&manifest_dir, "src/foundry").expect("foundry assets should collect");

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs. Do not edit by hand.\n\n");
    generated.push_str(&asset_array("CSS_ASSETS", &css));
    generated.push_str(&asset_array("JS_ASSETS", &js));
    generated.push_str(&asset_array("FOUNDRY_ASSETS", &foundry));

    fs::write(target, generated).expect("asset manifest should write");
}

fn collect_assets(manifest_dir: &Path, relative_dir: &str) -> io::Result<Vec<(String, PathBuf)>> {
    let root = manifest_dir.join(relative_dir);
    let mut assets = Vec::new();
    collect_recursive(manifest_dir, &root, &mut assets)?;
    assets.sort_by(|left, right| left.0.cmp(&right.0));
    println!("cargo:rerun-if-changed={}", root.display());
    Ok(assets)
}

fn collect_recursive(
    manifest_dir: &Path,
    current: &Path,
    assets: &mut Vec<(String, PathBuf)>,
) -> io::Result<()> {
    for entry in fs::read_dir(current)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_recursive(manifest_dir, &path, assets)?;
            continue;
        }

        let relative = path
            .strip_prefix(manifest_dir.join("src"))
            .expect("asset should be inside src")
            .to_string_lossy()
            .replace('\\', "/");
        assets.push((relative, path));
    }

    Ok(())
}

fn asset_array(name: &str, assets: &[(String, PathBuf)]) -> String {
    let mut output = format!("pub const {name}: &[Asset] = &[\n");
    for (relative, absolute) in assets {
        output.push_str("    Asset {\n");
        output.push_str(&format!("        path: {relative:?},\n"));
        output.push_str(&format!(
            "        contents: include_str!(r#\"{}\"#),\n",
            absolute.display()
        ));
        output.push_str("    },\n");
    }
    output.push_str("];\n\n");
    output
}
